# Hamon config generated by 'hamon new'
@use 8
@topology hypercube
@autoprefix 127.0.0.1:9001

# Roles
@node 0 @role coordinator
@node 1 @role worker
@node 2 @role worker
@node 3 @role worker
@node 4 @role worker
@node 5 @role worker
@node 6 @role worker
@node 7 @role worker

@job Commit
	@phase desc="add code" by=[*] task="git add ."
 	@phase desc="commit code" by=[*] task="git commit -am 'auto message'"
 	@phase desc="push code" by=[*] task="git push --all"
@end
